package com.nba.entities;
import lombok.Builder;
import lombok.Data;

import java.math.BigDecimal;
import java.net.URL;

/**
 * Sample product compare structure. Note that getters and setter are auto-generated by Lombok
 */
@Data
@Builder
public class PriceCompare {
    private BigDecimal price;
    private String source;
    private BigDecimal discountAmount;
    private URL productImageUrl;
}
